"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Clock3, FlaskConical, House, Search, Star, Stethoscope } from "lucide-react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { consultationTypeLabels, formatServiceDate, getUpcomingDates, mockDoctors, mockLabTests, type LabCategory } from "@/data/healthcare-services";
import { useHealthcareBooking } from "@/services/booking-context";
import { formatMoney } from "@/orders/pricing";
import { ChoiceButton, FormField, inputClass, MissingSelection, ServiceCard, ServicePageHeading, ServiceRouteFrame, StatusNote } from "@/components/services/service-ui";

const specialties = Array.from(new Set(mockDoctors.map((doctor) => doctor.specialty)));
const labCategories: Array<LabCategory | "All categories"> = ["All categories", "Wellness", "Diabetes care", "Heart health", "Thyroid care"];
const appointmentTimes = ["9:00 AM", "10:30 AM", "1:00 PM", "2:30 PM", "4:00 PM"];

function initials(name: string) {
  return name.replace("Dr. ", "").split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase();
}

export function ConsultationsPage() {
  const [query, setQuery] = useState("");
  const [specialty, setSpecialty] = useState("All specialties");
  const doctors = mockDoctors.filter((doctor) => {
    const matchesQuery = `${doctor.name} ${doctor.specialty}`.toLowerCase().includes(query.trim().toLowerCase());
    return matchesQuery && (specialty === "All specialties" || doctor.specialty === specialty);
  });

  return <ServiceRouteFrame><ServicePageHeading eyebrow="Doctor consultations" title="Thoughtful care starts with a conversation." description="Explore our sample care team, compare consultation options, and choose a time that works for you." />
    <section aria-label="Find a doctor" className="mb-7 rounded-2xl border border-line bg-white p-4 shadow-soft sm:p-5"><div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_240px]"><FormField label="Search doctors"><span className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} aria-hidden="true" /><input value={query} onChange={(event) => setQuery(event.target.value)} className={`${inputClass} pl-10`} type="search" placeholder="Name or specialty" /></span></FormField><FormField label="Specialty"><select value={specialty} onChange={(event) => setSpecialty(event.target.value)} className={inputClass}><option>All specialties</option>{specialties.map((option) => <option key={option}>{option}</option>)}</select></FormField></div><p className="mt-3 text-xs text-slate-500">{doctors.length} {doctors.length === 1 ? "doctor" : "doctors"} available in this sample directory</p></section>
    {doctors.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{doctors.map((doctor) => <ServiceCard key={doctor.id} className="flex flex-col"><div className="flex items-start gap-4"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-mint text-lg font-bold text-brand">{initials(doctor.name)}</span><div className="min-w-0"><h2 className="text-lg font-bold text-ink">{doctor.name}</h2><p className="mt-1 text-sm font-semibold text-brand">{doctor.specialty}</p><p className="mt-1 text-xs text-slate-500">{doctor.experienceYears} years experience</p></div></div><div className="mt-5 flex items-center justify-between gap-3"><span className="inline-flex items-center gap-1.5 rounded-full bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-800"><Star size={14} fill="currentColor" aria-hidden="true" />{doctor.rating.toFixed(1)} sample rating</span><span className="text-sm font-bold text-ink">{formatMoney.format(doctor.price)}<span className="font-medium text-slate-500"> / visit</span></span></div><p className="mt-4 flex items-center gap-2 text-xs font-semibold text-slate-600"><Clock3 size={15} className="text-brand" aria-hidden="true" />Sample availability: {doctor.nextAvailable}</p><div className="mt-4 flex flex-wrap gap-2">{doctor.consultationTypes.map((type) => <span key={type} className="rounded-full border border-line px-2.5 py-1 text-[11px] font-semibold text-slate-600">{consultationTypeLabels[type]}</span>)}</div><p className="mt-4 flex-1 text-sm leading-6 text-slate-600">{doctor.description}</p><Link href={`/consultations/${doctor.id}`} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-brand px-4 py-3 text-sm font-bold text-white transition hover:bg-brandDark focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand focus-visible:ring-offset-2">Book consultation <ArrowRight size={16} aria-hidden="true" /></Link></ServiceCard>)}</div> : <section className="rounded-3xl border border-dashed border-line bg-white px-6 py-14 text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-cloud text-slate-500"><Stethoscope size={22} aria-hidden="true" /></span><h2 className="mt-5 text-xl font-bold text-ink">No doctors match that search</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">Try another name or choose a different specialty to see more sample providers.</p><button onClick={() => { setQuery(""); setSpecialty("All specialties"); }} className="mt-5 rounded-xl border border-line px-4 py-2.5 text-sm font-bold text-brand focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">Clear filters</button></section>}
    <StatusNote>Provider profiles, experience, ratings, prices, and availability are sample information for this POC. No real clinician schedules are connected.</StatusNote>
  </ServiceRouteFrame>;
}

export function DoctorBookingPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const doctor = mockDoctors.find((entry) => entry.id === id);
  const { consultation, selectDoctor, updateConsultation } = useHealthcareBooking();
  const dates = getUpcomingDates();

  useEffect(() => { if (doctor) selectDoctor(doctor.id); }, [doctor, selectDoctor]);

  if (!doctor) return <ServiceRouteFrame><MissingSelection title="Doctor not found" description="Choose a doctor from the sample directory to view available consultation options." href="/consultations" linkText="Browse doctors" /></ServiceRouteFrame>;

  const ready = Boolean(consultation.doctorId === doctor.id && consultation.date && consultation.time && doctor.consultationTypes.includes(consultation.consultationType));
  return <ServiceRouteFrame><Link href="/consultations" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-brand hover:text-brandDark focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand"><ArrowLeft size={16} aria-hidden="true" />All doctors</Link><ServicePageHeading eyebrow="Book a consultation" title={doctor.name} description={`${doctor.specialty} · ${doctor.experienceYears} years experience · ${doctor.rating.toFixed(1)} sample rating`} />
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-6">
      <ServiceCard><h2 className="text-lg font-bold text-ink">About this doctor</h2><p className="mt-2 text-sm leading-6 text-slate-600">{doctor.description}</p><div className="mt-5 flex flex-wrap gap-2">{doctor.consultationTypes.map((type) => <ChoiceButton key={type} selected={consultation.consultationType === type} onClick={() => updateConsultation({ consultationType: type })}>{consultationTypeLabels[type]}</ChoiceButton>)}</div></ServiceCard>
      <ServiceCard><h2 className="text-lg font-bold text-ink">Choose a date</h2><p className="mt-1 text-sm text-slate-600">Sample openings over the next few weekdays.</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{dates.map((date) => <ChoiceButton key={date} selected={consultation.date === date} onClick={() => updateConsultation({ date })}>{formatServiceDate(date)}</ChoiceButton>)}</div><h3 className="mt-6 text-sm font-bold text-ink">Available times</h3><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{appointmentTimes.map((time) => <ChoiceButton key={time} selected={consultation.time === time} onClick={() => updateConsultation({ time })}>{time}</ChoiceButton>)}</div></ServiceCard>
    </div><aside className="h-fit rounded-2xl border border-line bg-white p-5 shadow-soft sm:p-6"><h2 className="text-lg font-bold text-ink">Consultation summary</h2><p className="mt-3 text-sm text-slate-600">{consultationTypeLabels[consultation.consultationType]}</p><p className="mt-1 text-xs text-slate-500">{consultation.date ? `${formatServiceDate(consultation.date)}${consultation.time ? ` · ${consultation.time}` : ""}` : "Choose a date and time"}</p><div className="mt-5 border-t border-line pt-4"><p className="text-xs text-slate-500">Sample consultation fee</p><p className="mt-1 text-2xl font-bold text-ink">{formatMoney.format(doctor.price)}</p></div><button disabled={!ready} onClick={() => router.push("/consultations/booking/details")} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-brand px-4 py-3 text-sm font-bold text-white transition hover:bg-brandDark focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:bg-slate-300">Continue to details <ArrowRight size={16} aria-hidden="true" /></button><p className="mt-3 text-xs leading-5 text-slate-500">No payment or live calendar connection.</p></aside></div>
  </ServiceRouteFrame>;
}

export function LabTestsPage() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<LabCategory | "All categories">("All categories");
  const tests = mockLabTests.filter((test) => {
    const matchesQuery = `${test.name} ${test.description} ${test.includedTests.join(" ")}`.toLowerCase().includes(query.trim().toLowerCase());
    return matchesQuery && (category === "All categories" || category === test.category);
  });

  return <ServiceRouteFrame><ServicePageHeading eyebrow="Lab tests" title="Clear testing options, made convenient." description="Browse sample tests and wellness packages, understand preparation, and choose a convenient home collection time." />
    <section aria-label="Find a lab test" className="mb-7 rounded-2xl border border-line bg-white p-4 shadow-soft sm:p-5"><div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_240px]"><FormField label="Search tests"><span className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} aria-hidden="true" /><input value={query} onChange={(event) => setQuery(event.target.value)} className={`${inputClass} pl-10`} type="search" placeholder="Test, package, or included marker" /></span></FormField><FormField label="Category"><select value={category} onChange={(event) => setCategory(event.target.value as LabCategory | "All categories")} className={inputClass}>{labCategories.map((option) => <option key={option}>{option}</option>)}</select></FormField></div><p className="mt-3 text-xs text-slate-500">{tests.length} {tests.length === 1 ? "test" : "tests"} in this sample catalog</p></section>
    {tests.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tests.map((test) => <ServiceCard key={test.id} className="flex flex-col"><div className="flex items-start justify-between gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-mint text-brand"><FlaskConical size={22} aria-hidden="true" /></span><span className="rounded-full bg-cloud px-3 py-1 text-xs font-bold text-slate-600">{test.category}</span></div><h2 className="mt-4 text-lg font-bold text-ink">{test.name}</h2><p className="mt-2 flex-1 text-sm leading-6 text-slate-600">{test.description}</p><div className="mt-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Included</p><ul className="mt-2 space-y-1 text-sm text-slate-600">{test.includedTests.slice(0, 3).map((item) => <li key={item}>• {item}</li>)}</ul>{test.includedTests.length > 3 && <p className="mt-1 text-xs font-semibold text-brand">+{test.includedTests.length - 3} more</p>}</div><p className="mt-4 flex items-center gap-2 text-xs font-semibold text-slate-600"><House size={15} className="text-brand" aria-hidden="true" />Home collection available</p><p className="mt-2 text-xs leading-5 text-slate-500">Preparation: {test.preparation}</p><div className="mt-4 flex items-end justify-between gap-3 border-t border-line pt-4"><span className="text-xs font-medium text-slate-500">Sample price</span><span className="text-lg font-bold text-ink">{formatMoney.format(test.price)}</span></div><Link href={`/lab-tests/${test.id}`} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-brand px-4 py-3 text-sm font-bold text-brand transition hover:bg-mint focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">View test & book <ArrowRight size={16} aria-hidden="true" /></Link></ServiceCard>)}</div> : <section className="rounded-3xl border border-dashed border-line bg-white px-6 py-14 text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-cloud text-slate-500"><FlaskConical size={22} aria-hidden="true" /></span><h2 className="mt-5 text-xl font-bold text-ink">No tests match those filters</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">Try a different test name or category to explore the sample catalog.</p><button onClick={() => { setQuery(""); setCategory("All categories"); }} className="mt-5 rounded-xl border border-line px-4 py-2.5 text-sm font-bold text-brand focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">Clear filters</button></section>}
    <StatusNote>Test information, prices, preparation, and sample collection availability are for demonstration only. Results and lab services are not connected.</StatusNote>
  </ServiceRouteFrame>;
}

export function LabTestBookingPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const test = mockLabTests.find((entry) => entry.id === id);
  const { labBooking, selectLabTest, updateLabBooking } = useHealthcareBooking();
  const dates = getUpcomingDates();

  useEffect(() => { if (test) selectLabTest(test.id); }, [test, selectLabTest]);

  if (!test) return <ServiceRouteFrame><MissingSelection title="Lab test not found" description="Choose a test from the sample catalog to review details and collection times." href="/lab-tests" linkText="Browse lab tests" /></ServiceRouteFrame>;

  const ready = Boolean(labBooking.testId === test.id && labBooking.date && labBooking.time);
  return <ServiceRouteFrame><Link href="/lab-tests" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-brand hover:text-brandDark focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand"><ArrowLeft size={16} aria-hidden="true" />All lab tests</Link><ServicePageHeading eyebrow="Book a lab test" title={test.name} description={`${test.category} · ${test.sampleType} · ${test.turnaround}`} />
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1.3fr)_320px]"><div className="space-y-6"><ServiceCard><h2 className="text-lg font-bold text-ink">What’s included</h2><ul className="mt-4 grid gap-2 sm:grid-cols-2">{test.includedTests.map((item) => <li className="rounded-xl bg-cloud px-4 py-3 text-sm text-slate-700" key={item}>{item}</li>)}</ul><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-line p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Preparation</p><p className="mt-2 text-sm leading-6 text-ink">{test.preparation}</p></div><div className="rounded-xl border border-line p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Collection</p><p className="mt-2 flex items-center gap-2 text-sm font-semibold text-ink"><House size={16} className="text-brand" aria-hidden="true" />Home collection available</p></div></div></ServiceCard>
      <ServiceCard><h2 className="text-lg font-bold text-ink">Choose a collection date</h2><p className="mt-1 text-sm text-slate-600">Select a sample home collection slot.</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{dates.map((date) => <ChoiceButton key={date} selected={labBooking.date === date} onClick={() => updateLabBooking({ date })}>{formatServiceDate(date)}</ChoiceButton>)}</div><h3 className="mt-6 text-sm font-bold text-ink">Available collection times</h3><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{appointmentTimes.map((time) => <ChoiceButton key={time} selected={labBooking.time === time} onClick={() => updateLabBooking({ time })}>{time}</ChoiceButton>)}</div></ServiceCard>
    </div><aside className="h-fit rounded-2xl border border-line bg-white p-5 shadow-soft sm:p-6"><h2 className="text-lg font-bold text-ink">Test summary</h2><p className="mt-3 text-sm leading-6 text-slate-600">{test.name}</p><p className="mt-1 text-xs text-slate-500">Home collection · {labBooking.date ? `${formatServiceDate(labBooking.date)}${labBooking.time ? ` · ${labBooking.time}` : ""}` : "Choose a collection time"}</p><div className="mt-5 border-t border-line pt-4"><p className="text-xs text-slate-500">Sample price</p><p className="mt-1 text-2xl font-bold text-ink">{formatMoney.format(test.price)}</p></div><button disabled={!ready} onClick={() => router.push("/lab-tests/booking/details")} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-brand px-4 py-3 text-sm font-bold text-white transition hover:bg-brandDark focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:bg-slate-300">Continue to details <ArrowRight size={16} aria-hidden="true" /></button><p className="mt-3 text-xs leading-5 text-slate-500">A demo booking only. No payment or lab connection.</p></aside></div>
  </ServiceRouteFrame>;
}
