"use client";

import { ArrowLeft, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import Link from "next/link";
import { useCart } from "@/cart/cart-context";
import { MedicineVisual } from "@/components/medicines/medicine-visual";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });

export function CartPage() {
  const { items, itemCount, subtotal, setQuantity, removeItem } = useCart();
  return <main className="min-h-[calc(100vh-72px)] bg-cloud"><div className="container-app py-8 sm:py-12">
    <Link href="/medicines" className="inline-flex items-center gap-2 rounded-lg py-2 text-sm font-bold text-brand focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand"><ArrowLeft size={17} aria-hidden="true" /> Continue browsing</Link>
    <div className="mt-4 flex items-end justify-between gap-3"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-brand">Your selection</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-ink sm:text-4xl">Shopping cart</h1></div><p className="text-sm font-medium text-slate-500">{itemCount} {itemCount === 1 ? "item" : "items"}</p></div>
    {items.length === 0 ? <section className="mt-8 rounded-3xl border border-dashed border-line bg-white px-6 py-16 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-mint text-brand"><ShoppingBag size={24} aria-hidden="true" /></span><h2 className="mt-5 text-xl font-bold text-ink">Your cart is waiting for a first pick</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">Explore the sample catalog and add a medicine to see your selection here.</p><Link href="/medicines" className="mt-6 inline-flex items-center justify-center rounded-xl bg-brand px-5 py-3 text-sm font-bold text-white transition hover:bg-brandDark focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand focus-visible:ring-offset-2">Browse medicines</Link></section> : <div className="mt-7 grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_340px]">
      <section aria-label="Cart items" className="grid gap-3">{items.map(({ medicine, quantity }) => <article key={medicine.id} className="grid grid-cols-[88px_minmax(0,1fr)] gap-4 rounded-2xl border border-line bg-white p-4 sm:grid-cols-[120px_minmax(0,1fr)_auto] sm:items-center sm:p-5"><MedicineVisual medicine={medicine} className="h-24 sm:h-28" /><div className="min-w-0"><p className="text-xs font-semibold text-brand">{medicine.brandName}</p><Link href={`/medicines/${medicine.id}`} className="mt-1 block truncate text-base font-bold text-ink hover:text-brand focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">{medicine.name}</Link><p className="mt-1 text-xs text-slate-500">{medicine.strength} · {medicine.pack}</p><p className="mt-2 text-sm font-bold text-ink">{money.format(medicine.price)} <span className="font-medium text-slate-500">each</span></p></div><div className="col-span-2 flex items-center justify-between border-t border-line pt-3 sm:col-span-1 sm:flex-col sm:items-end sm:border-0 sm:pt-0"><div className="inline-flex items-center rounded-xl border border-line p-0.5"><button type="button" disabled={quantity <= 1} aria-label={`Decrease ${medicine.name} quantity`} onClick={() => setQuantity(medicine.id, quantity - 1)} className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-cloud disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand"><Minus size={14} aria-hidden="true" /></button><span aria-live="polite" className="min-w-8 text-center text-sm font-bold">{quantity}</span><button type="button" aria-label={`Increase ${medicine.name} quantity`} onClick={() => setQuantity(medicine.id, quantity + 1)} className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-cloud focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand"><Plus size={14} aria-hidden="true" /></button></div><div className="flex items-center gap-3 sm:mt-3"><span className="text-sm font-bold text-ink">{money.format(medicine.price * quantity)}</span><button type="button" aria-label={`Remove ${medicine.name} from cart`} onClick={() => removeItem(medicine.id)} className="grid size-9 place-items-center rounded-lg text-slate-400 transition hover:bg-rose-50 hover:text-rose-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand"><Trash2 size={16} aria-hidden="true" /></button></div></div></article>)}</section>
      <aside className="rounded-2xl border border-line bg-white p-5 sm:p-6"><h2 className="text-lg font-bold text-ink">Cart summary</h2><div className="mt-5 flex items-center justify-between border-b border-line pb-4 text-sm"><span className="text-slate-600">Subtotal ({itemCount} {itemCount === 1 ? "item" : "items"})</span><span className="font-bold text-ink">{money.format(subtotal)}</span></div><p className="mt-4 text-xs leading-5 text-slate-500">Sample cart only. Review your delivery details in the demo checkout. No real payment is taken.</p><Link href="/checkout" className="mt-5 flex w-full items-center justify-center rounded-xl bg-brand px-4 py-3 text-sm font-bold text-white transition hover:bg-brandDark focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">Continue to checkout</Link><Link href="/medicines" className="mt-2 flex w-full items-center justify-center rounded-xl border border-line px-4 py-3 text-sm font-bold text-brand transition hover:bg-mint focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">Continue browsing</Link></aside>
    </div>}
  </div></main>;
}
